#import <Foundation/Foundation.h>
#import "NGSAppointmentTrackingInfoResponse.h"
#import "NGSProblemDetails.h"
#import "NGSApi.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface NGSAppointmentApi: NSObject <NGSApi>

extern NSString* kNGSAppointmentApiErrorDomain;
extern NSInteger kNGSAppointmentApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(NGSApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// @param eventFlowIdentifier 
/// @param portalIdentifier 
/// 
///  code:200 message:"",
///  code:404 message:""
///
/// @return NGSAppointmentTrackingInfoResponse*
-(NSURLSessionTask*) getAppointmentInfoWithEventFlowIdentifier: (NSString*) eventFlowIdentifier
    portalIdentifier: (NSString*) portalIdentifier
    completionHandler: (void (^)(NGSAppointmentTrackingInfoResponse* output, NSError* error)) handler;



@end
