#import <Foundation/Foundation.h>
#import "NGSCreateNoteRequest.h"
#import "NGSCreateNoteResponse.h"
#import "NGSNoteInfo.h"
#import "NGSProblemDetails.h"
#import "NGSApi.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface NGSNotesApi: NSObject <NGSApi>

extern NSString* kNGSNotesApiErrorDomain;
extern NSInteger kNGSNotesApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(NGSApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// @param portalIdentifier 
/// @param request 
/// @param xClientIdentifier Client Identifier (default to Set Client Identifier)
/// @param xAPIKey Client API Key (default to Set Key)
/// 
///  code:200 message:"",
///  code:400 message:""
///
/// @return NGSCreateNoteResponse*
-(NSURLSessionTask*) createNoteWithPortalIdentifier: (NSString*) portalIdentifier
    request: (NGSCreateNoteRequest*) request
    xClientIdentifier: (NSString*) xClientIdentifier
    xAPIKey: (NSString*) xAPIKey
    completionHandler: (void (^)(NGSCreateNoteResponse* output, NSError* error)) handler;


/// 
/// 
///
/// @param portalIdentifier 
/// @param xClientIdentifier Client Identifier (default to Set Client Identifier)
/// @param xAPIKey Client API Key (default to Set Key)
/// @param after  (optional)
/// @param limit  (optional) (default to 10)
/// 
///  code:200 message:"",
///  code:400 message:""
///
/// @return NSArray<NGSNoteInfo>*
-(NSURLSessionTask*) getNotesForPortalWithPortalIdentifier: (NSString*) portalIdentifier
    xClientIdentifier: (NSString*) xClientIdentifier
    xAPIKey: (NSString*) xAPIKey
    after: (NSString*) after
    limit: (NSNumber*) limit
    completionHandler: (void (^)(NSArray<NGSNoteInfo>* output, NSError* error)) handler;



@end
