#import <Foundation/Foundation.h>
#import "NGSCreatePreSignedUrlsRequest.h"
#import "NGSApi.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface NGSPhotosApi: NSObject <NGSApi>

extern NSString* kNGSPhotosApiErrorDomain;
extern NSInteger kNGSPhotosApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(NGSApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 
/// 
///
/// @param portalIdentifier 
/// @param albumIdentifier 
/// @param xClientIdentifier Client Identifier (default to Set Client Identifier)
/// @param xAPIKey Client API Key (default to Set Key)
/// 
///  code:200 message:""
///
/// @return NSURL*
-(NSURLSessionTask*) getPhotosForAlbumWithPortalIdentifier: (NSString*) portalIdentifier
    albumIdentifier: (NSString*) albumIdentifier
    xClientIdentifier: (NSString*) xClientIdentifier
    xAPIKey: (NSString*) xAPIKey
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// 
/// 
///
/// @param portalIdentifier 
/// @param xClientIdentifier Client Identifier (default to Set Client Identifier)
/// @param xAPIKey Client API Key (default to Set Key)
/// @param projectIdentifier  (optional)
/// 
///  code:200 message:""
///
/// @return NSURL*
-(NSURLSessionTask*) getPhotosForPortalWithPortalIdentifier: (NSString*) portalIdentifier
    xClientIdentifier: (NSString*) xClientIdentifier
    xAPIKey: (NSString*) xAPIKey
    projectIdentifier: (NSString*) projectIdentifier
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;


/// 
/// 
///
/// @param portalIdentifier 
/// @param request 
/// @param xClientIdentifier Client Identifier (default to Set Client Identifier)
/// @param xAPIKey Client API Key (default to Set Key)
/// @param projectIdentifier  (optional)
/// 
///  code:200 message:""
///
/// @return NSURL*
-(NSURLSessionTask*) getPreSignedUrlsWithPortalIdentifier: (NSString*) portalIdentifier
    request: (NGSCreatePreSignedUrlsRequest*) request
    xClientIdentifier: (NSString*) xClientIdentifier
    xAPIKey: (NSString*) xAPIKey
    projectIdentifier: (NSString*) projectIdentifier
    completionHandler: (void (^)(NSURL* output, NSError* error)) handler;



@end
