#import <Foundation/Foundation.h>
#import "NGSCreateProjectFeedbackRequest.h"
#import "NGSProblemDetails.h"
#import "NGSProjectFeedbackResponse.h"
#import "NGSApi.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface NGSPortalFeedbackApi: NSObject <NGSApi>

extern NSString* kNGSPortalFeedbackApiErrorDomain;
extern NSInteger kNGSPortalFeedbackApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(NGSApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Creates a job feedback based on event flow and portal.
/// 
///
/// @param portalIdentifier 
/// @param jobFeedbackRequest 
/// @param xClientIdentifier Client Identifier (default to Set Client Identifier)
/// @param xAPIKey Client API Key (default to Set Key)
/// 
///  code:200 message:"",
///  code:400 message:"",
///  code:404 message:""
///
/// @return NGSProjectFeedbackResponse*
-(NSURLSessionTask*) addPortalFeedbackWithPortalIdentifier: (NSString*) portalIdentifier
    jobFeedbackRequest: (NGSCreateProjectFeedbackRequest*) jobFeedbackRequest
    xClientIdentifier: (NSString*) xClientIdentifier
    xAPIKey: (NSString*) xAPIKey
    completionHandler: (void (^)(NGSProjectFeedbackResponse* output, NSError* error)) handler;



@end
