#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "NGSParticipantResponse.h"
#import "NGSState.h"
@protocol NGSParticipantResponse;
@class NGSParticipantResponse;
@protocol NGSState;
@class NGSState;



@protocol NGSAppointmentTrackingInfoResponse
@end

@interface NGSAppointmentTrackingInfoResponse : NGSObject


@property(nonatomic) NSString* eventFlowIdentifier;

@property(nonatomic) NGSParticipantResponse* owner;

@property(nonatomic) NGSParticipantResponse* recipient;

@property(nonatomic) NSString* taskDescription;

@property(nonatomic) NSString* destAddress;

@property(nonatomic) NGSState* stateCode;

@property(nonatomic) NSDate* onTheWayDate;

@property(nonatomic) NSDate* startDate;

@property(nonatomic) NSDate* arrivedDate;

@property(nonatomic) NSDate* completedDate;

@end
