#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "NGSPresignedPhotoInfo.h"
@protocol NGSPresignedPhotoInfo;
@class NGSPresignedPhotoInfo;



@protocol NGSCreatePreSignedUrlsRequest
@end

@interface NGSCreatePreSignedUrlsRequest : NGSObject


@property(nonatomic) NSArray<NGSPresignedPhotoInfo>* photos;

@end
