#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol NGSNoteInfo
@end

@interface NGSNoteInfo : NGSObject


@property(nonatomic) NSString* _id;

@property(nonatomic) NSString* text;

@property(nonatomic) NSDate* createDateTimeUtc;

@property(nonatomic) NSString* firstName;

@property(nonatomic) NSString* lastName;

@property(nonatomic) NSString* author;

@end
