#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "NGSPortalStatus.h"
#import "NGSState.h"
@protocol NGSPortalStatus;
@class NGSPortalStatus;
@protocol NGSState;
@class NGSState;



@protocol NGSPortalStatusResponse
@end

@interface NGSPortalStatusResponse : NGSObject


@property(nonatomic) NGSPortalStatus* status;

@property(nonatomic) NGSState* eventFlowState;

@property(nonatomic) NSString* eventFlowIdentifier;

@end
