#import <Foundation/Foundation.h>
#import "NGSObject.h"

/**
* Stardust API
* Stardust is the supporting API for the ProAssist app
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "NGSEntityBase.h"
#import "NGSPhoneNumberType.h"
#import "NGSStatus.h"
@protocol NGSEntityBase;
@class NGSEntityBase;
@protocol NGSPhoneNumberType;
@class NGSPhoneNumberType;
@protocol NGSStatus;
@class NGSStatus;



@protocol NGSPhoneNumber
@end

@interface NGSPhoneNumber : NGSEntityBase


@property(nonatomic) NSString* countryCode;

@property(nonatomic) NSString* areaCode;

@property(nonatomic) NSString* digits;

@property(nonatomic) NSString* extension;

@property(nonatomic) NSNumber* isValid;

@property(nonatomic) NGSStatus* status;

@property(nonatomic) NGSPhoneNumberType* phoneNumberType;

@property(nonatomic) NSString* notes;

@property(nonatomic) NSString* hashLookup;

@end
